name: Test Actions
on:
  workflow_dispatch:
   inputs:
      version: 
        description: '测试'
        required: false
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is ${env:SELECTED_COLOR}"
        
