name: Test Actions
on:
  workflow_dispatch:
   inputs:
      version: 
        description: '测试'
        required: false
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE
      
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

        
